### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by xkmy** [awmleer/reto#12]
作者您好!用了reto感觉非常喜欢,但是在使用上还有点疑惑,允许我问点问题哈!
如果有多个provider的话,除了一层层的写下去,嗯,还有别的办法吗,
还有就是每个store里的数据是自己单独管理好,还是由外部传入统一管理好,希望作者可以指点下!

reto牛批！

**Comment by awmleer** [comment]
hh非常感谢认可～

如果有多个 `Provider` 的话，一般的确是要一层层的写下去的，目前的 `Provider` 组件是只能一次provide一个Store的，但是如果你在项目中经常需要重复性的组合某几个Store的话，可以考虑自己封装成一个组件，比如说：

```jsx
const CommonProviders = (props) => (
  <Provider of={AccountStore}>
    <Provider of={OrdersStore}>
      <Provider of={OrdersStore}>
        {props.children}
      </Provider>
    </Provider>
  </Provider>
)
```

```jsx
const App = (props) => {
  return (
    <CommonProviders>
      {/* ... */}
    </CommonProviders>
  )
}
```

至于Store中的数据是自己单独管理还是外部传入，这个我觉得是个见仁见智的问题，不过我一般还是会在多个Store间建立起[依赖关系](https://reto.js.org/#/zh-cn/guide?id=store之间的依赖)。当然不同的场景还是要具体分析的，我写reto的时候还是希望能尽量保证灵活性，不增加一些太过主观的范式规则。。

希望能对您有所帮助😵如果还有其他疑问/建议/bug的话都随时欢迎反馈～

**Comment by xkmy** [comment]
感谢作者回复！哈哈哈，当初就是在用ts的时候实在是受不了redux的模板代码了，不用ts还好，用啦ts还要再写一堆redux相关的类型声明，几个函数写下来人都没了，有了reto妈妈再也不用担心hooks的状态管理啦！

希望reto越来越好！

**Comment by zhuchentong** [comment]
可以将Providers放到数组中进行合并，对外只需要引用暴露的Provider就好
```tsx
const providers: any[] = []

const ProvidersComposer = props =>
    props.providers.reduceRight(
        (children, Parent) => <Parent>{children}</Parent>,
        props.children
    )

export const Provider = props => {
    return (
        <ProvidersComposer providers={providers}>
            {props.children}
        </ProvidersComposer>
    )
}
```
