### ISSUE TITLE
触发子组件更新的时候在第二帧，这可能会引起一些消费状态不同步的问题

### ISSUE THREAD

**Issue by oychao** [awmleer/reto#14]
```javascript
/* eslint-disable react/no-array-index-key */
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider, useStore } from 'reto';

const Store = () => {
  const [list, setList] = React.useState([]);
  return { list, setList };
};

const BadGuy = () => {
  const { list, setList } = useStore(Store);
  const [activeIdx, setActiveIdx] = React.useState(0);

  function changeStore() {
    setList([...list, { val: Math.random() }]);
    setActiveIdx(list.length);
  }

  return (
    <div>
      <button type="button" onClick={changeStore}>
        Click Me! Twice!
      </button>
      <hr />
      <div style={{ color: 'red' }}>{activeIdx ? list[activeIdx].val : ''}</div>
      <ol>
        {list.map((item, idx) => (
          <li key={idx}>{item.val}</li>
        ))}
      </ol>
    </div>
  );
};

const App = () => (
  <Provider of={Store}>
    <BadGuy />
  </Provider>
);

ReactDOM.render(<App />, document.getElementById('root'));
```

如上例所示，子组件`BadGuy`里面有自己的状态`activeIdx`，渲染的时候需要同时使用`Provider`中的状态和本地组件。

**但是根据Reto的设计**，`setList`之后更新的是`Executor`（其中的`useEffect`，第一帧），然后再调用`Container`的`notify`，通知子组件更新“副本”（`useStore`中的`setState`，第二帧）。

但是`BadGuy`中的`activeIdx`却是在第一帧的时候就已经更新，此时`Executor`中的状态虽然被更新了，但是`useStore`中的副本却还没有触发更新，因此导致二者（全局状态和局部状态）结合使用时出错。

这个问题看看需要怎么处理比较合适。

**Comment by awmleer** [comment]
是的，这个的确是预期行为，之前我也注意到了，但是业务场景中很少会对两个状态的原子化更新有这么严苛的要求。
不过我还是会去看一下有没有解决的方法。

**Comment by oychao** [comment]
上面这个例子可能有点少见，为了保证页面不崩溃，加个`list[activeIdx] && list[activeIdx].val`也是可以的，但是如果出现同时更新reto管理的状态和组件内部状态，则组件一定会执行两次渲染，不仅仅是render方法执行，dom也会挂载两次（如果diff不一样的话），可能出现页面“闪跳一下”的情况。

**Comment by awmleer** [comment]
我觉得这个问题其实不仅仅是在 reto 中存在，在其他的状态管理库中也会出现，因为这涉及到如何把组件内和组件外的状态进行原子化的绑定。目前来看，这个问题更适合由开发者自己通过代码的设计来进行规避。。
