### ISSUE TITLE
Provider 在提供多个 Store 的时候，Store 之间内嵌是不是有顺序关系呀？内层的 Store 能引用外层的，反之不行！

### ISSUE THREAD

**Issue by andremao** [awmleer/reto#17]
src/index.js：
<img width="289" alt="图片" src="https://user-images.githubusercontent.com/48238671/90591129-d93b8000-e214-11ea-8588-26848d0f57e9.png">

如图，UserStore 中能引入 CounterStore，反之不行！

<img width="470" alt="图片" src="https://user-images.githubusercontent.com/48238671/90591203-0be57880-e215-11ea-9b17-348d54b01c2a.png">
<img width="503" alt="图片" src="https://user-images.githubusercontent.com/48238671/90591228-228bcf80-e215-11ea-92bd-95ab848eb567.png">

**Comment by awmleer** [comment]
是的，**被依赖**的Store要放在外面，先进行创建

**Comment by andremao** [comment]
> 是的，**被依赖**的Store要放在外面，先进行创建

嘿嘿，大佬您好，请问有单个 Store 实例，并且支持模块拆分的示例代码吗？

**Comment by awmleer** [comment]
这里有一些简单的demo：https://github.com/awmleer/reto-demo
然后这个是一个复杂一些的实际应用：https://github.com/markslide/markslide
