### ISSUE TITLE
如何实现持久化存储

### ISSUE THREAD

**Issue by zhuchentong** [awmleer/reto#18]
我发现了reto这个库，我觉着reto的写法简单明了，我使用在了我们的项目中，但是我遇到一个问题，我需要添加数据持久化存储的支持不知道应该如何处理，是否可以使用类似`redux-persist`的库作为支持

`
import rootReducer from './reducers'

const persistConfig = {
  key: 'root',
  storage,
}

`

**Comment by awmleer** [comment]
可以用 ahooks 工具库中的 [useLocalStorageState](https://ahooks.js.org/zh-CN/hooks/state/use-local-storage-state) 实现把 state 持久化到 local storage 中～
