### ISSUE TITLE
写给国王的建议

### ISSUE THREAD

**Issue by JiabingYang** [awmleer/reto#2]
原谅我是一个对React的了解只有读过官方Get Started的不会前端开发的天使，所以没看懂国王的代码...

作为一个前Android开发，Android里有个实现单向数据流的类似React的库，[MvRx](https://github.com/airbnb/MvRx)，里面也实现了自己的[Store](https://github.com/airbnb/MvRx/blob/master/mvrx/src/main/kotlin/com/airbnb/mvrx/RealMvRxStateStore.kt)，看一下不同平台的类似库，说不定能给你带来些启发～

**Comment by awmleer** [comment]
hh收到
非常感谢🙏🏻我一定好好研究一下

**Comment by life2015** [comment]
好家伙
