### ISSUE TITLE
感觉reto和hox的风格很类似，请问作者是如何看待两者各自的优势的？

### ISSUE THREAD

**Issue by LiuZhenyan-Wuzhong** [awmleer/reto#36]

**Comment by awmleer** [comment]
两者思路基本是一样的，hox 的 API 会稍微简洁一些，也支持了全局 store，后面大概率会主要迭代 hox～

**Comment by LiuZhenyan-Wuzhong** [comment]
谢谢作者回答，我感觉我的开发过程中对于状态管理最痛点的就是组件间共享状态，hox和reto都可以完全地，幽雅地解决了这个问题。作者牛逼。
