### ISSUE TITLE
官方文档的问题

### ISSUE THREAD

**Issue by UserRegistering** [awmleer/reto#5]
有可能是我理解不够，也有可能文档写的确实不清楚。至少是我有几点不清楚。
1.传递参数给store
文档上讲通过args属性，但是没有示例讲在store中怎么获取参数，怎么使用参数。
如果想要在组件中使用store的数据，并且向store中传参，就必须要使用withProvider了，是这个意思吗？
2.关于解决store频繁更新导致的性能问题
`const fooStore = useStore(FooStore, store => [store.x, store.y[0]])`
这里的store.y[0]在FooStore定义的时候并没有返回y这个属性，这里是不是写错了？

**Comment by awmleer** [comment]
1. 之所以叫“参数”，就是因为`args`本身就是Store函数的参数呀：

```jsx
<Provider of={FooStore} args={[1, 'test']}></Provider>

function FooStore(x, y) {
  // x === 1
  // y === 'test'
}
```

> 如果想要在组件中使用store的数据，并且向store中传参，就必须要使用withProvider了，是这个意思吗？

这个不是的，`Provider`和`withProvider`的本质的作用是一样的，上面的例子里面就是直接在`Provider`上加的`args`属性。

2. 这里的确文档写的有点误解，我其实本意是想表达返回值是个数组，可以有多个元素，不过和之前的`FooStore`定义有点冲突了，我后面会把文档改一下。。多谢指正～

**Comment by UserRegistering** [comment]
多谢你的回答，关于第二点还有一个小问题。useSotre第二个参数返回的数组，store..y[0]是不是说明，我们可以根据复杂的数据结构中的某个小数据的变化来更精准地控制该组件是否更新呢？

**Comment by awmleer** [comment]
hh是的，我当时文档这样写的初衷就是想表达这个意思

**Comment by UserRegistering** [comment]
感谢！
