### ISSUE TITLE
Using CommonJS Module Instead

### ISSUE THREAD

**Issue by siwei-lu** [awmleer/reto#6]
I had found `reto` a long time ago and I love it for real. Recently I'm trying to use it in one of my real projects.

It seemly can not work together with Jest since you bundle it in ES Module which is not supported by Node.js by default.

So I strongly suggest using CommonJS module instead.

Thanks for your work.

**Comment by awmleer** [comment]
Thanks for your suggestion! I have fixed this in v0.8.1 just now.

**Comment by awmleer** [comment]
If you meet any other problems, please feel free to open issues~

**Comment by siwei-lu** [comment]
So quick! So that I can go ahead my work tomorrow.
