### ISSUE TITLE
Why is `withProvider` remove?

### ISSUE THREAD

**Issue by siwei-lu** [awmleer/reto#7]
I think it's useful and can't be found in the latest version of `reto`. Therefore I have to manually wrap my components using `Provider`.

So I wonder why you removed it?

**Comment by siwei-lu** [comment]
Another thing is about the labels of issues.

It's better to set up a label of the issue when creating so that we can know what kind of it.

Github offers a set of labels. Use them plz.

**Comment by awmleer** [comment]
The main reasons why I removed `withProvider` are:

1. It is hard to make `withProvider` type strong. There are a lot of type inference issues.
2. `withProvider` makes the tracking of `Provider` usages hard. If you want to search where you have provided `FooStore`, you have to search for both `<Provider of={FooStore}/>` and `withProvider({of: FooStore})`.
3. Learning and understanding the syntax of `withProvider` is not that easy for most developers.

**But don't worry! There is an alternative for `withProvider`:**

[github.com/awmleer/with-wrapper](https://github.com/awmleer/with-wrapper)

You can install `with-wrapper` and use it instead. For example:

```jsx
export const App = withWrapper(element => (
  <Provider of={FooStore}>
    {element}
  </Provider>
))(props => {
  const fooStore = useStore(FooStore)
  return (
    <div>app</div>
  )
})
```

I'm very very sorry for the missing of documentation and the confusion I have caused! I'll add these instructions to the docs later.

**Comment by siwei-lu** [comment]
I made #8 . hope you will love it.
